# SecretStore — connects ESO to AWS Secrets Manager
# Uses the eso-sa ServiceAccount which has IRSA permissions to read secrets
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: color-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa
