replicaCount: 2

image:
  repository: 068704208379.dkr.ecr.us-east-1.amazonaws.com/color-app
  pullPolicy: IfNotPresent
  tag: "v2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  port: 8080

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

env:
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: color-app-secret
        key: SECRET_KEY
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: color-app-secret
        key: DB_PASSWORD
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: color-app-secret
        key: API_KEY

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60

volumes:
  - name: app-data
    persistentVolumeClaim:
      claimName: color-app-pvc

volumeMounts:
  - name: app-data
    mountPath: /usr/src/app/data

nodeSelector: {}

tolerations: []

affinity: {}

namespace:
  create: true
  name: production

configmap:
  enabled: true
  data:
    APP_COLOR: "purple"
    APP_ENV: "production"
    APP_MESSAGE: "Hello, Jesus is Lord!"

secretStore:
  enabled: true
  name: color-app-ss
  region: us-east-1

externalSecret:
  enabled: true
  refreshInterval: "1m"
  secretStoreRef:
    name: color-app-ss
    kind: SecretStore
  data:
    - secretKey: SECRET_KEY
      remoteKey: color-app/prod
      property: SECRET_KEY
    - secretKey: DB_PASSWORD
      remoteKey: color-app/prod
      property: DB_PASSWORD
    - secretKey: API_KEY
      remoteKey: color-app/prod
      property: API_KEY

loadBalancer:
  enabled: true
  port: 80

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: "gp2"
