{{- if .Values.esoServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: {{ .Values.namespace.name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.esoServiceAccount.roleArn }}
{{- end }}
