apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "color-app.fullname" . }}-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ include "color-app.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "color-app.fullname" . }}-secret
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.keys }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ $.Values.externalSecret.remoteKey }}
      property: {{ .name }}
  {{- end }}
