{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "color-app.fullname" . }}-lb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    {{- include "color-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.loadBalancer.port }}
      targetPort: 8080
{{- end }}
