apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "color-app.fullname" . }}-secret-store
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "color-app.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecret.serviceAccountName }}
